In [1]:
import pandas as pd

In [2]:
info = {
      "name" : ["hari","pandu"],
      "cgpa"  : [9.3,10]
   }

df = pd.DataFrame(info)
print(df)

    name  cgpa
0   hari   9.3
1  pandu  10.0

In [3]:
df

    name  cgpa
0   hari   9.3
1  pandu  10.0

In [4]:
#second way to create a pandas dataframe
df = pd.DataFrame([["adam",24],["bob",23]])
print(df)

      0   1
0  adam  24
1   bob  23

In [5]:
df

      0   1
0  adam  24
1   bob  23

In [ ]:
#we can create using numpy arrays